language: node_js
node_js:
- 4.0.0
before_script:
- npm install -g gulp
script:
- gulp travis
sudo: false
deploy:
  provider: heroku
  app: bettybotssi
  skip_cleanup: true
  api_key:
    secure: jC1pRHWKY8DtloNgjaSUxirLJeJmDpNrzpYwr1T6wdeT6smuKgfLgjDOD8SWEIvsK9+lhzwdXab4k/c3kmMb059kp1APqDGqOhfRvuR/hfokH1d4rO10yv6Gi/KHUGysmOwj6RgGqDCgAjeoucOkSUxP9UsSNBerrciEdq+dU3zR0Jk9hR5QLol1UPT8m4lQ9d+9FxRLAu+tS8haQsjsMBAmtOK0mkq3gCh6pMkoilj5ou9RPulQ/vmJ7Syt23awV+Tnwqh56WGluSXaT7lDSWsZWjK/35jLBvJ5byVCGnDnW80QuALdIgVmBK5TvWUXq2A+1zNKtzsujaaHvim2shYljGrAJA+k/K2IvWrnQpaX7UrqLRIL0pHpiJE9GVns9PXNfMOK6G86fwy6jFxo87Pwa2irTZ32MlGMb0DDf2X9IZAc88PN1ew/hjpkXLwb7K5Q5vpH79pqkVCvqZ7bRND7OwLMGQQ7hvTZ/jNs8lRHtM0NHOvfEmInTxS632RBZcdy02FVTHR07/QInGRconAl1gVwNMZrZ7KO6gxNwrz0O5QHkGfkEH543J37vAfZQKOjfJpgkE96ipgyl9aSBlNQqrv7V5zYvEYjvI7ipnTn+4tX62QcUP4Awhn4f0KewfBe+1oKSROfP7Qs69NhRxSDHi+3w5PuZwRYCVQTmnk=
